version: '3'
services:
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  streaming_webserver:
    build: ./twitter_streaming/
    image: twitter_stream_webserver:latest
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    env_file:
      - env_files/.env.dev
  mongodb:
    image: mongo
    restart: always
    env_file:
      - mongodb/mongo_auth.env
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - mongodb/mongo_auth.env
    depends_on:
      - mongodb